---

- name: Install pip3
  package: name=python3-pip update_cache=yes
  when: python_compose_module

- name: Install python setuptools
  package: name=python3-setuptools update_cache=yes
  when: python_compose_module

- name: Install python3 compose module
  pip: name=docker-compose executable=pip3
  when: python_compose_module
