---

- name: Add key
  rpm_key: key=https://download.docker.com/linux/centos/gpg

- name: Add repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Configure docker repo
  ini_file:
    dest: /etc/yum.repos.d/docker.repo
    section: "docker-ce-{{ docker_update_channel }}"
    option: enabled
    value: "1"

- name: Centos 8 or newer requirement
  dnf:
    name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"
  when: ansible_distribution_major_version > '7'
