---

- name: Detect Centos 8 
  fail: msg="Centos 8 is unsupported platform!"
  when: ansible_distribution_major_version == "8"

- name: Add key
  rpm_key: key=https://download.docker.com/linux/centos/gpg

- name: Add repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Configure docker repo
  ini_file:
    dest: /etc/yum.repos.d/docker.repo
    section: "docker-ce-{{ docker_update_channel }}"
    option: enabled
    value: "1"
