---

- name: ca private
  openssl_privatekey:
    path: "{{ ca_key_path }}"
- name: ca csr
  openssl_csr:
    path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_key_path }}"
    common_name: '*'
    basic_constraints:
     - 'CA:TRUE'
    basic_constraints_critical: yes
- name: ca cert
  openssl_certificate:
    path: "{{ ca_crt_path }}"
    csr_path: "{{ ca_csr_path }}"
    privatekey_path: "{{ ca_key_path }}"
    provider: selfsigned
  register: ca_crt
- name: server key
  openssl_privatekey:
    path: "{{ server_key_path }}"
- name: server csr
  openssl_csr:
    path: "{{ server_csr_path }}"
    privatekey_path: "{{ server_key_path }}"
    common_name: '*'
- name: server cert
  openssl_certificate:
    path: "{{ server_crt_path }}"
    csr_path: "{{ server_csr_path }}"
    provider: ownca
    ownca_path: "{{ ca_crt_path }}"
    ownca_privatekey_path: "{{ ca_key_path }}"
- name: client key
  openssl_privatekey:
    path: "{{ client_key_path }}"
  register: client_key
- name: client csr
  openssl_csr:
    path: "{{ client_csr_path }}"
    privatekey_path: "{{ client_key_path }}"
- name: client cert
  openssl_certificate:
    path: "{{ client_crt_path }}"
    csr_path: "{{ client_csr_path }}"
    provider: ownca
    ownca_path: "{{ ca_crt_path }}"
    ownca_privatekey_path: "{{ ca_key_path }}"
  register: client_crt

- name: test existing listen tcp
  shell: "grep -c 2376 {{ docker_systemd_unit_path }} || true"
  register: grep
- name: append dockerd listen on tcp
  lineinfile:
    path: "{{ docker_systemd_unit_path }}"
    regexp: '^(ExecStart=.*)$'
    line: '\1 -H tcp://0.0.0.0:2376'
    backrefs: true
  when: grep.stdout == "0"

- name: restart dockerd
  systemd:
    name: docker
    daemon_reload: true
    state: restarted
