---

- name: Ensure sudoer
  when: sudo
  lineinfile:
    path: "/etc/sudoers.d/{{ user }}"
    line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
    create: yes
    state: "{{ state }}"

- name: Manage primary group
  group:
    name: "{{ user_group }}"

- name: Manage user
  user:
    name: "{{ user }}"
    group: "{{ user_group }}"
    groups: "{{ user_groups }}"
    state: "{{ state }}"
    shell: /bin/bash

- name: Set authorized key
  when: pubkey and state != "absent"
  authorized_key:
    user: "{{ user }}"
    key: "{{ pubkey }}"
    exclusive: "{{ pubkey_exclusive }}"

- name: Manage password authentication
  notify: restart sshd
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^(.*)PasswordAuthentication (.*)"
    line: "PasswordAuthentication {{ password_auth | ternary('yes', 'no') }}"
